<a href="https://colab.research.google.com/github/YashuSingh005/do-it-yawrrr/blob/main/SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Connecting and WOrking with in memory database (SQLite)**

In [ ]:
import sqlite3
import pandas as pd
connection = sqlite3.connect(':memory')
cursor = connection.cursor() # create a cursor object  to execute sql command

In [ ]:
create_table_query = '''

CREATE TABLE table_name (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER,
    email TEXT UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

'''
cursor.execute(create_table_query)
print("student is created ")

student is created

In [ ]:
insert_data_query = '''
INSERT INTO table_name (name, age, email)
VALUES
    ('Alice Smith', 25, 'alice@example.com'),
    ('Bob Jones', 30, 'bob@example.com'),
    ('Charlie Brown', 22, 'charlie@example.com'),
    ('David Miller', 28, 'david@example.com'),
    ('Emma Wilson', 24, 'emma@example.com'),
    ('Frank Thomas', 35, 'frank@example.com'),
    ('Grace Davis', 29, 'grace@example.com');
'''
cursor.execute(insert_data_query)
connection.commit()
print("data has been inserted..")

data has been inserted..

In [ ]:
query = 'SELECT * FROM table_name;'
df = pd.read_sql(query, connection)
df

   id           name  age                email           created_at
0   1    Alice Smith   25    alice@example.com  2026-09-18 17:50:30
1   2      Bob Jones   30      bob@example.com  2026-09-18 17:50:30
2   3  Charlie Brown   22  charlie@example.com  2026-09-18 17:50:30
3   4   David Miller   28    david@example.com  2026-09-18 17:50:30
4   5    Emma Wilson   24     emma@example.com  2026-09-18 17:50:30
5   6   Frank Thomas   35    frank@example.com  2026-09-18 17:50:30
6   7    Grace Davis   29    grace@example.com  2026-09-18 17:50:30

In [ ]:
update = 'UPDATE table_name SET name = "Alice Johnson" WHERE id = 1;'
cursor.execute(update)
connection.commit()
print("data has been updated..")

data has been updated..

In [ ]:
cursor.close()
connection.close()

# **Connecting MYSQl database using pymysql**

In [ ]:

# !pip install pymysql
import pymysql
host = '
port = 13043
user = ''
password = ''
database = 'defaultdb'

In [ ]:
connection = pymysql.connect(host=host,
                            port=port,
                            user=user,
                            password=password,
                            database=database,
                            cursorclass = pymysql.cursors.DictCursor # this will return result as Dictionary
                            )
cursor = connection.cursor()
print("connected to db ")

connected to db

In [ ]:
create_table_query = """
CREATE TABLE IF NOT EXISTS employees (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    salary DECIMAL(10, 2) NOT NULL,
    department_id INT
);
"""

add_data_query = """
INSERT INTO employees (first_name, last_name, email, salary, department_id)
VALUES (%s, %s, %s, %s, %s)
ON DUPLICATE KEY UPDATE email=email;
"""

data_values = [
    ('Grace', 'Singh', 'grace.singh@example.com', 75000.00, 101),
    ('Alex', 'Rivera', 'alex.r@example.com', 68000.00, 102),
    ('Sam', 'Chen', 'sam.c@example.com', 82000.00, 101)
]

# 3. Execute
with connection.cursor() as cursor:
    # Step 1: Create Table
    cursor.execute(create_table_query)

    # Step 2: Add Data
    cursor.executemany(add_data_query, data_values)

    # Step 3: Commit
    connection.commit()

print("Table created and data added successfully!")

Table created and data added successfully!

In [ ]:
with connection.cursor(pymysql.cursors.DictCursor) as cursor:
    cursor.execute("SELECT * FROM employees;")
    rows = cursor.fetchall()

    print("--- EMPLOYEES LIST ---")
    for row in rows:
        # print(f"ID: {row['id']} | Name: {row['first_name']} {row['last_name']} | Email: {row['email']} | Salary: ${row['salary']}")
        print(row)

--- EMPLOYEES LIST ---
{'id': 1, 'first_name': 'Grace', 'last_name': 'Singh', 'email': 'grace.singh@example.com', 'salary': Decimal('75000.00'), 'department_id': 101}
{'id': 2, 'first_name': 'Alex', 'last_name': 'Rivera', 'email': 'alex.r@example.com', 'salary': Decimal('68000.00'), 'department_id': 102}
{'id': 3, 'first_name': 'Sam', 'last_name': 'Chen', 'email': 'sam.c@example.com', 'salary': Decimal('82000.00'), 'department_id': 101}

In [ ]:
cursor.close()
connection.close()

# **Using mysql connector in python**

In [ ]:

!pip install mysql-connector-python
import mysql.connector

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.7.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (11 kB)
Downloading mysql_connector_python-26.7.0-cp313-cp313-manylinux_2_28_x86_64.whl (21.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.7/21.7 MB 73.1 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.7.0

In [ ]:
from mysql.connector import Error

In [ ]:
try :
    connection = mysql.connector.connect(
    host = '',
    port = 13043,
    user = '',
    password = '',
    database = 'defaultdb'
        )
    if connection.is_connected():
        db_info = connection.get_server_info()
        print("Connected to MySQL Server version ", db_info)
        cursor = connection.cursor()
except mysql.connector.Error as e:
    print("Error while connecting to MySQL", e)

Connected to MySQL Server version  8.4.8

/tmp/ipykernel_1220/3723078070.py:10: DeprecationWarning: Call to deprecated function get_server_info. Reason:
    The property counterpart 'server_info' should be used instead.

  db_info = connection.get_server_info()

In [ ]:
cursor.execute("SELECT * FROM employees")
rows = cursor.fetchall()
for row in rows:
    print(row)

(1, 'Grace', 'Singh', 'grace.singh@example.com', Decimal('75000.00'), 101)
(2, 'Alex', 'Rivera', 'alex.r@example.com', Decimal('68000.00'), 102)
(3, 'Sam', 'Chen', 'sam.c@example.com', Decimal('82000.00'), 101)

In [ ]:
# Check if 'connection' exists and is open
if 'connection' in locals() and connection.is_connected():
    # Close the cursor
    cursor
    # Check if 'cursor' exists and close it safely
    if 'cursor' in locals() and cursor:
        cursor.close()

    # Close the connection
    connection.close()
    print("Connection is closed...")

Connection is closed...

# **Connecting with Pandas**

In [ ]:
# !pip install mysql.connector-python SQLALchemy
import pandas as pd

In [69]:
from sqlalchemy import create_engine

user = 'avnadmin'
password = ''
host = ''
port = 13043
database = 'defaultdb'

connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(connection_string)

In [71]:

query = '''SELECT * FROM employees'''
df = pd.read_sql(query, con=engine)
df

   id first_name last_name                    email   salary  department_id
0   1      Grace     Singh  grace.singh@example.com  75000.0            101
1   2       Alex    Rivera       alex.r@example.com  68000.0            102
2   3        Sam      Chen        sam.c@example.com  82000.0            101

## you can run many more command

### CLOSING THE SQLALCHEMY

In [74]:
engine.dispose() # also can use with postrgess same method